### ISSUE TITLE
Can this be used to perform openSUSE upgrades?

### ISSUE THREAD

**Issue by maverick74** [yast/yast-migration#62]
Would be great to be able to use this to perform upgrades on openSUSE Leap (15.3->15.4) and maybe in tumbleweed (to avoid getting to the terminal)

(Such as in https://hackweek.opensuse.org/projects/easy-opensuse-upgrade)

**Comment by lslezak** [comment]
This module implements the SLE migrations (SP1 -> SP2,... or Leap -> SLES), openSUSE Leap uses a completely different migration process. So far we do not plan to support Leap migrations here.

**Comment by shundhammer** [comment]
This is a question that we answered dozens, if not hundreds of times before, in the last 15-20 years. This is the upgrade equivalent of the "live installer" that we dropped many years before for good reasons, yet it keeps coming back to live as someone's pet projects, yet none of its problems that we buried it for has a solution.

What we offer is a distro upgrade with a reboot from the installation media, as described in the manuals. This boots from a USB stick or a DVD into a well-defined environment, the _inst-sys_. That inst-sys contains all the things that we need for a system installation or upgrade; and it contains them in the right versions and in the right combinations, just as we need it for that process. There are no nasty surprises because of incompatible of missing libraries or tools.

However, if we start something similar from a user's running system, we have no such guarantees; the user might have installed different versions of those libaries, some may not be there at all. And it's the same with system utilities.

Over time, we learned the lesson with the _live installer_ that this may work, or mit may not. If it works, we are saving the user one reboot (and the hassle of copying the installation / upgrade ISO image to a USB stick or to burn it to a DVD). If it doesn't work, the end user may end up with a botched installation; or, worse, with a botched upgrade, so the resulting system is unusable where the previous one probably worked fine.

The SLE migration is a bit different, and it has less risk of having become too incompatible, because that well-defined environment is what a SLE customer gets warranty for, so there is a strong incentive not to modify it in too incompatible ways (yet that may happen as well, of course).

**Comment by maverick74** [comment]
Hi. Thanks for your reply. 
I didn't find your reasons anywhere else, hence the bug creation.

I see...

But it still puzzles me how *buntu does it (not to mention Win)?

And... If "zypper --releasever=xx.x dup" what's the diference? Wouldn't it be the same thing running below?

**Comment by shundhammer** [comment]
Doing this the zypper way as described in the manual is a completely different approach; this was added many years after the YaST upgrade workflow existed.

YaST does this independently of zypper; it doesn't just fire off a bunch of zypper commands). At the same time, you get many more degrees of freedom; for example, if there are package dependency problems, you get into the interactive package manager where you can remove or add packages as you like. You can also change a lot of other settings. It basically gives you (almost) the same degrees of freedom as a new installation.

Using those zypper commands is very limiting in many ways; basically, it just points your repos to the new ones and does a `zypper dup`. This may or may not be what a user wants. Losing the degrees of freedom and the ways of manual intervention in the process if something does not go quite the way you want is the price you pay.

I believe Ubuntu does it in a very similar way, but I am not absolutely sure.

And don't get me started about the Windows installation / upgrade process; I have been fighting with the prejudice that this is so great all my professional life (since the late 1990s). Basically, it does its own thing without much regard to the user's wishes; you have to take it or leave it.

**Comment by maverick74** [comment]
> Using those zypper commands is very limiting in many ways; basically, it just points your repos to the new ones and does a `zypper dup`. This may or may not be what a user wants. Losing the degrees of freedom and the ways of manual intervention in the process if something does not go quite the way you want is the price you pay.

This is something i could perfectly live with. Also this would be an **Off-by-default** option with all those usual warnings _with the skulls, meme's and death tunes representations it deserves..._

I also believe (not sure either) ubuntu does something similar to zypper dup.

**Comment by shundhammer** [comment]
> > Using those zypper commands is very limiting in many ways; basically, it just points your repos to the new ones and does a `zypper dup`. This may or may not be what a user wants. Losing the degrees of freedom and the ways of manual intervention in the process if something does not go quite the way you want is the price you pay.
> 
> This is something i could perfectly live with.

The problem is that we went through this situation many times before: A compromise is agreed upon with a big and well-understood caveat; it's not perfect, but it is accepted as a compromise.

And in my personal experience it doesn't take long until somebody who was not part of the compromise comes along and starts complaining that it's not perfect (i.e. that the compromise is indeed a compromise) and demands that it needs to be made perfect.

This happens every time. Worse, more often than not those demanding perfection where a compromise was the only reason why we accepted to do it in the first place are product managers who come late to the game.

Been there. Done that. Got the T-shirt; a whole drawer full of them, actually. ;-)

**Comment by maverick74** [comment]
LOLOL. XD

Yes, i must agree you are absolutely right in your points. It shows that either _by having to many t-shirts_ or by intuition you do understand well human psychology. There will always be someone asking for more.

But that happens everytime, everywhere. we all try to catch the uncatchable perfection. The question is: should we stop innovating just because we'll never get to a perfect state and will have a lot of people asking for even more? (don't we have that already, anyway?!)
